server:
  port: 8080

spring:
  application:
    name: assistive-hub-backend
  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} # 24시간 (milliseconds)

encryption:
  secret:
    key: ${ENCRYPTION_SECRET_KEY}

# OAuth Configuration for all integrations
slack:
  client:
    id: ${SLACK_CLIENT_ID:dummy}
    secret: ${SLACK_CLIENT_SECRET:dummy}
  redirect:
    uri: ${SLACK_REDIRECT_URI:http://localhost:3000/integrations/slack/callback}

github:
  client:
    id: ${GITHUB_CLIENT_ID:dummy}
    secret: ${GITHUB_CLIENT_SECRET:dummy}
  redirect:
    uri: ${GITHUB_REDIRECT_URI:http://localhost:3000/integrations/github/callback}

gitlab:
  client:
    id: ${GITLAB_CLIENT_ID:dummy}
    secret: ${GITLAB_CLIENT_SECRET:dummy}
  redirect:
    uri: ${GITLAB_REDIRECT_URI:http://localhost:3000/integrations/gitlab/callback}
  url: ${GITLAB_URL:https://gitlab.com}

notion:
  client:
    id: ${NOTION_CLIENT_ID:dummy}
    secret: ${NOTION_CLIENT_SECRET:dummy}
  redirect:
    uri: ${NOTION_REDIRECT_URI:http://localhost:3000/integrations/notion/callback}

logging:
  level:
    com.assistivehub: DEBUG
    org.springframework.security: DEBUG
