server:
  port: 8080

spring:
  application:
    name: assistive-hub-backend
  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} # 24시간 (milliseconds)

encryption:
  secret:
    key: ${ENCRYPTION_SECRET_KEY}

# Slack OAuth Configuration
slack:
  client:
    id: ${SLACK_CLIENT_ID}
    secret: ${SLACK_CLIENT_SECRET}
  redirect:
    uri: ${SLACK_REDIRECT_URI:http://localhost:3000/integrations/slack/callback}

logging:
  level:
    com.assistivehub: DEBUG
    org.springframework.security: DEBUG
